package org.togetherincouncil.mobile.ui.onboarding

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.selection.selectableGroup
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.togetherincouncil.mobile.data.remote.dto.Role

@Composable
fun OnboardingScreen(viewModel: OnboardingViewModel, onDone: () -> Unit) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    var apiKeyText by remember { mutableStateOf("") }

    LaunchedEffect(uiState) {
        if (uiState is OnboardingUiState.Done) onDone()
    }

    Scaffold { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.Center
        ) {
            Text("Together in Council", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
            Spacer(Modifier.height(8.dp))
            Text(
                "Sign in with the API key your council admin gave you.",
                style = MaterialTheme.typography.bodyMedium
            )
            Spacer(Modifier.height(24.dp))

            when (val state = uiState) {
                is OnboardingUiState.NeedsManualRole -> ManualRoleStep(
                    onConfirm = { username, role -> viewModel.confirmManualRole(username, role) }
                )
                else -> ApiKeyStep(
                    apiKeyText = apiKeyText,
                    onApiKeyChange = { apiKeyText = it },
                    isValidating = state is OnboardingUiState.Validating,
                    errorMessage = (state as? OnboardingUiState.Error)?.message,
                    onSubmit = { viewModel.submitApiKey(apiKeyText) }
                )
            }

            Spacer(Modifier.height(24.dp))
            Text(
                "API keys are generated by an admin (php database/generate_api_key.php) and don't expire " +
                    "— ask your council admin if you don't have one.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}

@Composable
private fun ApiKeyStep(
    apiKeyText: String,
    onApiKeyChange: (String) -> Unit,
    isValidating: Boolean,
    errorMessage: String?,
    onSubmit: () -> Unit
) {
    OutlinedTextField(
        value = apiKeyText,
        onValueChange = onApiKeyChange,
        label = { Text("API key") },
        singleLine = true,
        enabled = !isValidating,
        keyboardOptions = KeyboardOptions(imeAction = ImeAction.Done),
        modifier = Modifier.fillMaxWidth()
    )

    if (errorMessage != null) {
        Spacer(Modifier.height(8.dp))
        Text(errorMessage, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodyMedium)
    }

    Spacer(Modifier.height(16.dp))
    Button(
        onClick = onSubmit,
        enabled = !isValidating && apiKeyText.isNotBlank(),
        modifier = Modifier.fillMaxWidth()
    ) {
        if (isValidating) {
            CircularProgressIndicator(modifier = Modifier.size(18.dp), strokeWidth = 2.dp)
        } else {
            Text("Continue")
        }
    }
}

@Composable
private fun ManualRoleStep(onConfirm: (username: String, role: Role) -> Unit) {
    var username by remember { mutableStateOf("") }
    var selectedRole by remember { mutableStateOf<Role?>(null) }

    Text(
        "This server doesn't have api/whoami.php yet, so we can't look up your role automatically. " +
            "What's your username and role?",
        style = MaterialTheme.typography.bodyMedium
    )
    Spacer(Modifier.height(16.dp))
    OutlinedTextField(
        value = username,
        onValueChange = { username = it },
        label = { Text("Username") },
        singleLine = true,
        modifier = Modifier.fillMaxWidth()
    )
    Spacer(Modifier.height(16.dp))
    Column(Modifier.selectableGroup()) {
        listOf(Role.VIEWER, Role.MEMBER, Role.CLERK, Role.ADMIN).forEach { role ->
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.fillMaxWidth()
            ) {
                RadioButton(selected = selectedRole == role, onClick = { selectedRole = role })
                Text(role.name.lowercase().replaceFirstChar { it.uppercase() })
            }
        }
    }
    Spacer(Modifier.height(16.dp))
    Button(
        onClick = { selectedRole?.let { onConfirm(username, it) } },
        enabled = username.isNotBlank() && selectedRole != null,
        modifier = Modifier.fillMaxWidth()
    ) {
        Text("Continue")
    }
}
